name: Fake
version: "${pom.version}"
api: ["1.0.7"]
author: PetteriM1
main: idk.plugin.fake.Main

commands:
  fake:
    description: Add or remove fake player
    usage: "/fake <add|remove> <name>"
    permission: fake.use
  fakerandomquery:
    description: Enable radom fake player count in query only
    usage: "/fakerandomquery <on <base, min, max, rand min, rand max>|off>"
    permission: fake.use
permissions:
  fake.use:
    description: "Allow usage of /fake"
    default: op