name: Fake
version: "1.0"
api: ["1.0.0"]
author: PetteriM1
main: idk.plugin.fake.Main

commands:
  fake:
    description: Add or remove fake player
    usage: "/fake <add|remove> <name>"
    permission: fake.use
permissions:
  fake.use:
    description: "Allow usage of /fake"
    default: op